version: 2.1

executors:
  node-executor:
    docker:
      - image: circleci/node:14

jobs:
  build-and-test:
    executor: node-executor
    steps:
      - checkout  # Checks out your code
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package-lock.json" }}
      - run:
          name: Install dependencies
          command: npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package-lock.json" }}
      - run:
          name: Run tests
          command: npm test  

  sonar-scan:
    docker:
      - image: sonarsource/sonar-scanner-cli:latest  # Use the SonarScanner CLI
    steps:
      - checkout
      - run:
          name: Run SonarCloud Analysis
          command: |
            sonar-scanner \
              -Dsonar.organization="thiyan-ouwish" \
              -Dsonar.projectKey="thiyan-ouwish_customer-portal" \
              -Dsonar.sources="src"  # Adjust path to your source code
              -Dsonar.host.url="https://sonarcloud.io" \
              -Dsonar.login=$SONAR_TOKEN  # Use the SONAR_TOKEN env variable

workflows:
  version: 2
  build-test-and-scan:
    jobs:
      - build-and-test
      - sonar-scan:
          requires:
            - build-and-test
